---
abstract: 'Catalyst view to resize images for thumbnails.'
author:
  - 'Nick Logan <ug@skunkds.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-GD-Thumbnail
no_index:
  directory:
    - t
    - inc
requires:
  Image::Info: 0
  Image::Resize: 0
  List::Util: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-View-GD-Thumbnail
version: 0.12
